### ISSUE TITLE
[Bug] {Ingestion Server} Cleanup fails from type mismatch

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#238]
## Description

Recently in production, the cleanup steps on the ingestion server `INGEST_UPSTREAM` task failed with the following error output:

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/ingestion_server/ingestion_server/tasks.py", line 106, in run
    reload_upstream(self.model)
  File "/ingestion_server/ingestion_server/ingest.py", line 293, in reload_upstream
    clean_image_data(table)
  File "/ingestion_server/ingestion_server/cleanup.py", line 290, in clean_image_data
    pool.starmap(_clean_data_worker, jobs)
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: '<' not supported between instances of 'str' and 'float'
```

This means that when comparing tags, tags with an "accuracy" property are somehow strings, and fail when attempting to compare them to our 	TAG_MIN_CONFIDENCE` constant.

https://github.com/WordPress/openverse-api/blob/3768ebced5d70f919e595e227ca0dd02c19f5cf2/ingestion_server/ingestion_server/cleanup.py#L106-L106

We should probably only make the comparison if the tag accruracy is a `float`, or otherwise attempt to convert the string.

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Additional context

I'd like to see an example of which rows have these `accuracy` fields as strings, and try to fix them earlier in the pipeline, but it seems quite a difficult or computationally expensive thing to query for.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I guess I was thinking it makes sense to do this kind of cleanup/normalizing as early in the ingestion process as possible, but maybe it does make sense for the upstream data to be super messy and this script handle more use cases?
