### ISSUE TITLE
Related media view returns 500

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#807]
## Description

It would appear that the related media page on `main` is returning 500s, here's the exception I get when visiting a `related_url` on `main`:

```python
web_1               | [2022-07-20 17:45:23,475 - django.request - 241][ERROR] [e95d22f7b9f1444e90f44b09f435c2be] Internal Server Error: /v1/images/c608767c-a696-4d07-9bc1-daf174ca724d/related/
web_1               | Traceback (most recent call last):
web_1               |   File "/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
web_1               |     response = get_response(request)
web_1               |   File "/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
web_1               |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1               |   File "/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1               |     return view_func(*args, **kwargs)
web_1               |   File "/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
web_1               |     return self.dispatch(request, *args, **kwargs)
web_1               |   File "/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
web_1               |     response = self.handle_exception(exc)
web_1               |   File "/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
web_1               |     self.raise_uncaught_exception(exc)
web_1               |   File "/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
web_1               |     raise exc
web_1               |   File "/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
web_1               |     response = handler(request, *args, **kwargs)
web_1               |   File "/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
web_1               |     return bound_method(*args, **kwargs)
web_1               |   File "/api/catalog/api/views/media_views.py", line 104, in related
web_1               |     results, num_results = related_media(
web_1               |   File "/api/catalog/api/controllers/elasticsearch/related.py", line 57, in related_media
web_1               |     f"results={json.dumps(results)}"
web_1               |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
web_1               |     return _default_encoder.encode(obj)
web_1               |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
web_1               |     chunks = self.iterencode(o, _one_shot=True)
web_1               |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
web_1               |     return _iterencode(o, 0)
web_1               |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
web_1               |     raise TypeError(f'Object of type {o.__class__.__name__} '
web_1               | TypeError: Object of type Hit is not JSON serializable
```

On first glance it looks like this might have been introduced in #790

## Reproduction

1. `just up`
2. Visit http://localhost:8000/v1/images/?q=car
3. Click on the `related_url` for a result
4. See error.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Ah! I swore I had squashed all those.

Why do the integration tests not catch this, I wonder?

To fix this we need to call `as_dict` on the `Hit` object.
